version: "3.9"

services:

  # Database
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres
    networks:
      - net

  # Application
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - database
    links:
      - database
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  pgdata:
    driver: local
