version: "3.9"

services:

  # Database
  rent_x_database:
    image: postgres
    container_name: rent_x_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres

  # Application
  rent_x_api:
    build: .
    container_name: rent_x_api
    restart: always
    ports:
      - ${API_PORT}:3333
      - 9229:9229 # For debug purposes
    volumes:
      - .:/usr/app
    depends_on:
      - rent_x_database
    links:
      - rent_x_database

volumes:
  pgdata:
    driver: local
