version: "3.9"

services:
  # Database
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  # Application
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 # For debug
    volumes:
      - .:/usr/app
    links:
      - database_rentx
    depends_on:
      - database_rentx

volumes:
  pgdata:
    driver: local
