name: Coveralls

on:
  push:
    branches: [ main ]

jobs:
  run:
    name: Report coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install dependencies
      run: yarn

    - name: Collect coverage
      run: yarn jest --passWithNoTests --coverage

    - name: Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: "Unit"
